# Данные:

Входные данные: 

`Столбцы EQ-EZ, имена столбцов (U1a, U1b, U1c, Uz, Up, Un, KdUa, KdUb, KdUc, KdU)`

Выходные:

`Столбец VS, имя столбца OZZ`

In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np
from test_model import *

In [2]:
df1 = pd.read_csv('data/splitted/cropped/cropped_csv/d1_c.csv', delimiter=";")
df2 = pd.read_csv('data/splitted/cropped/cropped_csv/d2_c.csv', delimiter=";")
df3 = pd.read_csv('data/splitted/cropped/cropped_csv/d3_c.csv', delimiter=";")
df4 = pd.read_csv('data/splitted/cropped/cropped_csv/d4_c.csv', delimiter=";")
df5 = pd.read_csv('data/splitted/cropped/cropped_csv/d5_c.csv', delimiter=";")
test = pd.read_csv('data/splitted/cropped/cropped_csv/test.csv', delimiter=";")

# Все данные (столбцы только из п.1)

In [3]:
frames = [df1, df2, df3, df4, df5, test]
data_df = pd.concat(frames)
data_df = data_df.drop(columns=['I1a', 'I1b', 'I1c', 'Iz', 'Ip', 'In', 'KdIa',  'KdIb', 'KdIc', 'KdI', 'PhiU1a', 'PhiU1b', 'PhiU1c'])
data_df

,U1a,U1b,U1c,Uz,Up,Un,KdUa,KdUb,KdUc,KdU,OZZ
0,63.0905,62.8107,63.3138,0.3127,63.0707,0.2598,2.6250,2.9247,2.6381,2.7293,0.00
1,63.0681,62.8197,63.3171,0.3115,63.0673,0.2765,2.6215,2.9331,2.6422,2.7323,0.00
2,63.1047,62.8153,63.3293,0.3130,63.0821,0.2598,2.6304,2.9411,2.6464,2.7393,0.00
3,63.0799,62.7894,63.3027,0.3131,63.0563,0.2612,2.6232,2.9188,2.6331,2.7250,0.00
4,63.0771,62.8203,63.3006,0.3135,63.0650,0.2631,2.6191,2.9301,2.6215,2.7236,0.00
...,...,...,...,...,...,...,...,...,...,...,...
95,103.2781,22.3849,87.1007,48.5101,62.4335,0.3894,4.5383,23.0148,5.3302,10.9611,8.82
96,103.2279,22.9554,86.5644,48.2244,62.4476,0.3864,4.6349,22.9249,5.4971,11.0190,8.82
97,62.8001,62.4415,62.9949,0.3482,62.7445,0.2338,2.1516,2.5926,2.1164,2.2869,0.00
98,62.7955,62.4296,62.9859,0.3475,62.7360,0.2309,2.1500,2.5818,2.1101,2.2806,0.00
99,102.9601,22.7010,86.7614,48.1063,62.4514,0.3978,4.6831,23.4132,5.5248,11.2070,8.82

# Количество данных для каждого значения OZZ

`для 6.44 очень мало данных, возможно поэтому получен сомнительный результат для 6.44`

In [4]:
data_df.groupby('OZZ').size()

OZZ
0.00    154821
1.69       408
3.64       917
5.11       363
6.44       187
8.82       231
dtype: int64

# Работа обученной модели

### Чтение модели и предсказание

In [5]:
h5_model = read_model_h5("test_normalized_data.h5")
x_data, y_data = read_normalized_test_data("data/splitted/cropped/cropped_csv/test_normalized.csv")
prediction_result = run_predictions(x_data, h5_model)

4/4 [==============================] - 0s 660us/step

### Вывод результатов

In [6]:
processed_result = predictions_processing(prediction_result)
print_predicted_and_true_data(processed_result, y_data)

Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 3.65; True: 3.64
Predicted: 3.67; True: 3.64
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 3.63; True: 3.64
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 1.67; True: 1.69
Predicted: 1.7; True: 1.69
Predicted: 1.7; True: 1.69
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 5.09; True: 5.11
Predicted: 5.1; True: 5.11
Predicted: 5.12; True: 5.11
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 5.11; True: 5.11
Predicted: 5.11; True: 5.11
Predicted: 5.11; True: 5.11
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 4.32; True: 6.44
Predicted: 4.32; True: 6.44
Predicted: 4.32; True: 6.44
Predicted: 4.32; True: 6.44
Predicted: 8.82; True: 8.82
Predicted: 8.81; True: 8.82
Predicted: 8.81; True: 8.82
Predicted: 8.81; True: 8.82
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 8.8; True: 8.82
Predicted: 8.81; True: 8.82
Predicted: 8.77; True: 8.82
Predicted: 0.0; True: 0.0
Predicted: 0.0; True: 0.0
Predicted: 8.81; True: 8.82